Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kio' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/knotifications #test dependency' : '@same'

Options:
  test-before-installing: True
