Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kio' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/knotifications' : '@same'
    'frameworks/kxmlgui' : '@same'
    'libraries/phonon' : '@stable'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
